name: ci

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Random Decide for Submitting
        id: random_decision
        run: echo "should_commit=$(( $RANDOM % 2 ))" >> $GITHUB_ENV

      - name: Conditional commit
        if: env.should_commit == '1'
        run: |
          git config --local user.email "2978124440@qq.com"
          git config --local user.name "John"
          # 设置远程仓库地址
          git remote set-url origin https://github.com/Valeri04jekeLo9uil05ggoqzano/cop
          git pull --rebase
          git commit --allow-empty -m "Make Program Every Day!"
          git push
